name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ketiko/gh-cache-action@main

      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"

      - uses: sbt/setup-sbt@v1

      - name: Download Dependencies
        run: sbt update

      - name: test:compile
        run: sbt test:compile
